### ISSUE TITLE
Upload from buffer

### ISSUE THREAD

**Issue by akonyushevskiy** [xmaestro/wistia-js#1]
What a correct way to upload with buffer? 

```
const WistiaUpload = wistia.WistiaUpload();
const videoStream = streamifier.createReadStream(video);

const uploadSettings = {
    project_id: config.wistia.project,
    file: videoStream,
    name: filename
};

WistiaUpload.upload(uploadSettings, (error, data) => {
   console.log(error, data);
});
```

I have next error:
```
Error: Server responded with error: 500
    at Request._callback (/Users/u/node/project/node_modules/wistia-js/util.js:126:31)
    at Request.self.callback (/Users/u/node/project/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/u/node/project/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/u/node/project/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) undefined
```
What i'm doing wrong, is there are any difference between fs.createReadString() and streamifer.createReadStream() ?

**Comment by xmaestro** [comment]
There should be no difference. And it's `fs.createReadStream` (https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options).

**Comment by xmaestro** [comment]
Closing because of lack of activity.
